/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:486b4916-071e-4188-9682-b30ab116b08d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wZHwrmHXm",
    "aws_user_pools_web_client_id": "4a4mehuliqtm3mpjbhnbarfgje",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://mvga5jafafdlvcbdx2ywh565ym.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yuqoacilhzf7bokmfso4rfj6bi",
    "aws_user_files_s3_bucket": "todoliststorage4eb449-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
